#!/usr/bin/env bash
# Look for the process ID (PID) of the 4-to_infinity_and_beyond process

target_pid=$(pgrep -f "4-to_infinity_and_beyond")

if [ -n "$target_pid" ]; then
    kill "$target_pid"
    echo "Terminated"
else
    echo "Process not found"
fi
