#!/usr/bin/env bash
# This script displays the content of the current directory in a list format

for file in *; do
    if [ -f "$file" ] && [[ ! "$file" == .* ]]; then
        echo "${file#*-}"
    fi
done
