#!/usr/bin/env bash
# Check if running in Docker

if grep -q 'docker' /proc/1/cgroup; then
    echo "Running inside Docker container"
    echo "Configuring hosts file..."
    
    # Modify hosts file
    sudo sed -i 's/^127.0.0.1.*localhost$/127.0.0.2 localhost/' /etc/hosts
    sudo sed -i 's/^.*facebook.com.*$/8.8.8.8 facebook.com/' /etc/hosts
    
    echo "Configuration complete."
else
    echo "This script should be run inside a Docker container."
    exit 1
fi
